export const TAB_TYPE = {
  ATTEND: 0
}

export const GIFT_CON_TYPE = {
  NORMAL: 0,
  WINNER: 1
}

export const GIFT_ROTATION_TYPE = {
  FAILD: 1,
  ONE_DAL: 2,
  GIFT_CHOCO: 4,
  GIFT_CONVENIENCE: 5,
  GIFT_STARBUCKS: 6,
  GIFT_VOUCHER: 7,
  GIFT_CHICKEN: 8,
  HUNDRED_DAL: 9,
  HUNDRED_DAL_2: 19,
  HUNDRED_DAL_3: 29,
  HUNDRED_DAL_4: 39,
  HUNDRED_DAL_5: 49,
  HUNDRED_DAL_6: 59,
  GIFT_SONGE: 14,
  GIFT_BARISTA: 15,
  GIFT_BASKIN: 16,
  GIFT_BURGERKING: 17,
  GIFT_DOMINO: 18,
  GIFT_SNEAKERS: 24,
  GIFT_PARIS: 25,
  GIFT_EDIYA: 26,
  GIFT_MOMS: 27,
  GIFT_BASKINBOX: 28,
  GIFT_DOCTORYOU: 34,
  GIFT_MINUTEMAID: 35,
  GIFT_DUNKINMUNCHKINS: 36,
  GIFT_BURGERKINGMONSTER: 37,
  GIFT_PARISBAGUETTECAKE: 38,
  GIFT_BANANAMILK: 44,
  GIFT_BINCH: 45,
  GIFT_DUNKINAMERDONUT: 46,
  GIFT_BASKINROBBINSPINT: 47,
  GIFT_DOMINOPIZZA: 48,
  GIFT_VITA500: 54,
  GIFT_HERSHEYSICEBAR: 55,
  GIFT_STARBUCKSLATTE: 56,
  GIFT_MOMSTOUCHUNBELIEVABLE: 57,
  GIFT_GOOBNEFULLMOON: 58,
  EXP1: 10001,
  EXP3: 10002,
  EXP5: 10003,
  EXP10: 10004
}

export const WIN_TYPE = {
  ALL: 0,
  NEW: 1
}
