export const TAB_TYPE = {
  ATTEND: 0
}

export const GIFT_CON_TYPE = {
  NORMAL: 0,
  WINNER: 1
}

export const GIFT_ROTATION_TYPE = {
  FAILD: 1,
  ONE_DAL: 2,
  GIFT_CHOCO: 4,
  GIFT_CONVENIENCE: 5,
  GIFT_STARBUCKS: 6,
  GIFT_VOUCHER: 7,
  GIFT_CHICKEN: 8,
  HUNDRED_DAL: 9,
  HUNDRED_DAL_2: 19,
  HUNDRED_DAL_3: 29,
  GIFT_SONGE: 14,
  GIFT_BARISTA: 15,
  GIFT_BASKIN: 16,
  GIFT_BURGERKING: 17,
  GIFT_DOMINO: 18,
  GIFT_SNEAKERS: 24,
  GIFT_PARIS: 25,
  GIFT_EDIYA: 26,
  GIFT_MOMS: 27,
  GIFT_BASKINBOX: 28
}

export const WIN_TYPE = {
  ALL: 0,
  NEW: 1
}
