
###
//API명 : 회원로그인
POST https://devapi2.dalbitcast.com/member/login
content-type: application/x-www-form-urlencoded

{
    "memType":"p",
    "memId": "010-1234-1234",
    "memPwd": "1234",
    "os" : 1
}
###

###
//API명 : 회원가입
POST https://devapi2.dalbitcast.com/member/signup
content-type: application/x-www-form-urlencoded

{
    "memType":"p",
    "memId": "010-1234-1234",
    "memPwd":"1234",
    "gender": "m",
    "nickNm": "radiogaga",
    "birthYY":1980,
    "birthMM":11,
    "birthDD":23,
    "term1":"y",
    "term2":"y",
    "term3":"y",
    "name":"홍길동",
    "os":3
}
###

###
//API명 :닉네임 중복체크 
GET https://devapi2.dalbitcast.com/member/nick
content-type: application/x-www-form-urlencoded

{
    "nickNm":"radiogaga",
}
###

###
//API명 :비밀번호 변경
POST https://devapi2.dalbitcast.com/member/pwd
content-type: application/x-www-form-urlencoded

{
    "memId":"010-1234-1234",
    "memPwd":"1234"
}
###

###
//API명 : 프로필편집
POST https://devapi2.dalbitcast.com/mypage/profile
content-type: application/x-www-form-urlencoded

{
    "gender":"m",
    "nickNm":"radiogaga",
    "name":"홍길동",
    "birthYY":1980,
    "birthMM":11,
    "birthDD":23
}
###

###
//API명 : 팬 등록
POST https://devapi2.dalbitcast.com/mypage/pan
content-type: application/x-www-form-urlencoded

{
    "memNo":"'11577931027280"
}
###

###
//API명 : 팬 해제
DELETE https://devapi2.dalbitcast.com/mypage/pan
content-type: application/x-www-form-urlencoded

{
    "memNo":"'11577931027280"
}
###

###
//API명 : 정보조회
GET https://devapi2.dalbitcast.com/profile
content-type: application/x-www-form-urlencoded

{
    "memNo":"'11577931027280"
}
###

###
//API명 : 회원방송방 기본설정 조회하기 
GET https://devapi2.dalbitcast.com/mypage/broad
content-type: application/x-www-form-urlencoded

{
    
}
###

###
//API명 : 회원 정보 조회
GET https://devapi2.dalbitcast.com/mypage
content-type: application/x-www-form-urlencoded

{
    
}
###

###
//API명 : 회원 방송방 기본설정 수정하기
POST https://devapi2.dalbitcast.com/mypage/broad
content-type: application/x-www-form-urlencoded

{
    "roomType":1,
    "title":"title",
    "wecomMsg":"환영합니다",
    "isEntry":0,
    "isAge":0
}
###

###
//API명 : 회원 신고하기
POST https://devapi2.dalbitcast.com/mypage/declar
content-type: application/x-www-form-urlencoded

{
    "memNo":"'11577931027280",
    "reason":1,
    "cont":"신고내용",
}
###

###
//API명 : 회원 차단하기
POST https://devapi2.dalbitcast.com/mypage/block
content-type: application/x-www-form-urlencoded

{
    "memNo":"'11577931027280"
}
###


###
//API명 : 회원 해제하기
DELETE https://devapi2.dalbitcast.com/mypage/block
content-type: application/x-www-form-urlencoded

{
    "memNo":"'11577931027280"
}
###

###
//API명 : 회원 알림설정 조회하기
GET https://devapi2.dalbitcast.com/mypage/notify
content-type: application/x-www-form-urlencoded

{
    
}
###

###
//API명 : 회원 알림설정 수정하기
POST https://devapi2.dalbitcast.com/mypage/notify
content-type: application/x-www-form-urlencoded

{
    "isAll":0,
    "isFanReg":0,
    "isBoard":0,
    "isStarCast":1,
    "isStarNoti":1,
    "isEvtNoti":1,
    "isSearch":1
}
###

###
//API명 : 회원 팬보드 댓글 달기
POST https://devapi2.dalbitcast.com/profile/board
content-type: application/x-www-form-urlencoded

{
    "memNo":"11577931027280",
    "depth":1,
    "boardNo":1,
    "content":"댓글입니다."
}
###

###
//API명 : 회원 팬보드 목록조회
GET https://devapi2.dalbitcast.com/profile/board
content-type: application/x-www-form-urlencoded

{
    "memNo":"11577931027280",
    "page":1,
    "records":10
}
###

###
//API명 : 회원 팬보드 대댓글 조회하기
GET https://devapi2.dalbitcast.com/profile/board/reply
content-type: application/x-www-form-urlencoded

{
    "memNo":"11577931027280",
    "boardNo":5
}
###