
###
//API명 : 회원로그인
POST https://devapi2.dalbitcast.com/member/login
content-type: application/x-www-form-urlencoded

{
    "s_mem":"p",
    "s_id": "010-1234-1324",
    "s_pwd": "1234",
    "i_os" : 1
}
###

###
//API명 : 회원가입
POST https://devapi2.dalbitcast.com/member/signup
content-type: application/x-www-form-urlencoded

{
    "s_mem":"p",
    "s_id": "010-1234-1324",
    "s_gender": "m",
    "s_nickNm": "radiogaga",
    "i_birthYY":1980,
    "i_birthMM":11,
    "i_birthDD":23,
    "s_term1":"y",
    "s_term2":"y",
    "s_term3":"y",
    "s_name":"홍길동",
    "i_os":1
}
###

###
//API명 :닉네임 중복체크 
GET https://devapi2.dalbitcast.com/member/nick
content-type: application/x-www-form-urlencoded

{
    "s_nickNm":"radiogaga",
}
###

###
//API명 :비밀번호 변경
POST https://devapi2.dalbitcast.com/member/pwd
content-type: application/x-www-form-urlencoded

{
    "s_phoneNo":"010-1234-1324",
    "s_pwd":"1234"
}
###

###
//API명 : 프로필편집
POST https://devapi2.dalbitcast.com/mypage/profile
content-type: application/x-www-form-urlencoded

{
    "s_gender":"m",
    "s_nickNm":"radiogaga",
    "s_name":"홍길동",
    "i_birthYY":1980,
    "i_birthMM":11,
    "i_birthDD":23
}
###

###
//API명 : 팬 등록
POST https://devapi2.dalbitcast.com/mypage/pan
content-type: application/x-www-form-urlencoded

{
    "s_mem_no":"'11577931027280"
}
###

###
//API명 : 팬 해제
DELETE https://devapi2.dalbitcast.com/mypage/pan
content-type: application/x-www-form-urlencoded

{
    "s_mem_no":"'11577931027280"
}
###

###
//API명 : 정보조회
GET https://devapi2.dalbitcast.com/profile
content-type: application/x-www-form-urlencoded

{
    "s_mem_no":"'11577931027280"
}
###

###
//API명 : 회원방송방 기본설정 조회하기 
GET https://devapi2.dalbitcast.com/mypage/broad
content-type: application/x-www-form-urlencoded

{
    
}
###

###
//API명 : 회원 정보 조회
GET https://devapi2.dalbitcast.com/mypage
content-type: application/x-www-form-urlencoded

{
    
}
###

###
//API명 : 회원 방송방 기본설정 수정하기
POST https://devapi2.dalbitcast.com/mypage/broad
content-type: application/x-www-form-urlencoded

{
    "i_type":1,
    "s_title":"title",
    "s_welcome":"환영합니다",
    "i_entry":0,
    "i_age":0
}
###

###
//API명 : 회원 신고하기
POST https://devapi2.dalbitcast.com/mypage/declar
content-type: application/x-www-form-urlencoded

{
    "s_mem_no":"'11577931027280",
    "i_reason":1,
    "s_cont":"신고내용",
}
###

###
//API명 : 회원 차단하기
POST https://devapi2.dalbitcast.com/mypage/block
content-type: application/x-www-form-urlencoded

{
    "s_mem_no":"'11577931027280"
}
###


###
//API명 : 회원 해제하기
DELETE https://devapi2.dalbitcast.com/mypage/block
content-type: application/x-www-form-urlencoded

{
    "s_mem_no":"'11577931027280"
}
###